Description: Base VPC Template - 1x VPC, 1x IGW, 12 subnets (3x public subnets, 3x
  database subnets, 3x application subnets, 3 alternate subnets), route tables and
  routes.
Parameters:
  Project:
    Description: Give the project a name
    Type: String
    Default: ZaraJoy
  VPCCIDR:
    Description: VPC CIDR Range
    Type: String
    Default: 10.0.0.0/16
  Environment:
    Description: What type of Environment is this?
    Type: String
    AllowedValues:
      - Dev
      - Test
      - Production
      - QA
    Default: Dev
  AZsUsed:
    Description: Select how many AZs should the network span (1-3)
    Type: String
    AllowedValues:
      - '1'
      - '2'
      - '3'
    Default: '2'
Conditions:
  3AZ: !Equals [!Ref AZsUsed, '3']
  2AZ: !Or [ !Condition 3AZ, !Equals [!Ref AZsUsed, '2']]
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Tags
        Parameters:
          - Project
          - Environment
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - VPC
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - IGW
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref 'VPC'
      InternetGatewayId: !Ref 'InternetGateway'
  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref 'VPC'
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - RouteTablePublic
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  RouteTablePublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref 'RouteTablePublic'
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'InternetGateway'
  RouteTableAssociationPublicA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref 'SubnetPublicA'
      RouteTableId: !Ref 'RouteTablePublic'
  RouteTableAssociationPublicB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: 2AZ
    Properties:
      SubnetId: !Ref 'SubnetPublicB'
      RouteTableId: !Ref 'RouteTablePublic'
  RouteTableAssociationPublicC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: 3AZ
    Properties:
      SubnetId: !Ref 'SubnetPublicC'
      RouteTableId: !Ref 'RouteTablePublic'
  SubnetDatabaseA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      CidrBlock: !Select
        - 0
        - !Cidr
          - !GetAtt 'VPC.CidrBlock'
          - 16
          - 12
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - subnet-database-A
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  SubnetDatabaseB:
    Type: AWS::EC2::Subnet
    Condition: 2AZ
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      CidrBlock: !Select
        - 1
        - !Cidr
          - !GetAtt 'VPC.CidrBlock'
          - 16
          - 12
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - subnet-database-B
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  SubnetDatabaseC:
    Type: AWS::EC2::Subnet
    Condition: 3AZ
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - 2
        - !GetAZs ''
      CidrBlock: !Select
        - 2
        - !Cidr
          - !GetAtt 'VPC.CidrBlock'
          - 16
          - 12
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - subnet-database-C
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  SubnetApplicationA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      CidrBlock: !Select
        - 3
        - !Cidr
          - !GetAtt 'VPC.CidrBlock'
          - 16
          - 12
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - subnet-application-A
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  SubnetApplicationB:
    Type: AWS::EC2::Subnet
    Condition: 2AZ
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      CidrBlock: !Select
        - 4
        - !Cidr
          - !GetAtt 'VPC.CidrBlock'
          - 16
          - 12
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - subnet-application-A
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  SubnetApplicationC:
    Type: AWS::EC2::Subnet
    Condition: 3AZ
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - 2
        - !GetAZs ''
      CidrBlock: !Select
        - 5
        - !Cidr
          - !GetAtt 'VPC.CidrBlock'
          - 16
          - 12
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - subnet-application-A
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  SubnetPublicA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      MapPublicIpOnLaunch: true
      CidrBlock: !Select
        - 6
        - !Cidr
          - !GetAtt 'VPC.CidrBlock'
          - 16
          - 12
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - subnet-public-A
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  SubnetPublicB:
    Type: AWS::EC2::Subnet
    Condition: 2AZ
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      MapPublicIpOnLaunch: true
      CidrBlock: !Select
        - 7
        - !Cidr
          - !GetAtt 'VPC.CidrBlock'
          - 16
          - 12
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - subnet-public-B
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  SubnetPublicC:
    Type: AWS::EC2::Subnet
    Condition: 3AZ
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - 2
        - !GetAZs ''
      MapPublicIpOnLaunch: true
      CidrBlock: !Select
        - 8
        - !Cidr
          - !GetAtt 'VPC.CidrBlock'
          - 16
          - 12
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - subnet-public-C
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  SubnetAlternateA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - 0
        - !GetAZs ''
      CidrBlock: !Select
        - 9
        - !Cidr
          - !GetAtt 'VPC.CidrBlock'
          - 16
          - 12
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - subnet-alternate-A
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  SubnetAlternateB:
    Type: AWS::EC2::Subnet
    Condition: 2AZ
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - 1
        - !GetAZs ''
      CidrBlock: !Select
        - 10
        - !Cidr
          - !GetAtt 'VPC.CidrBlock'
          - 16
          - 12
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - subnet-alternate-B
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
  SubnetAlternateC:
    Type: AWS::EC2::Subnet
    Condition: 3AZ
    Properties:
      VpcId: !Ref 'VPC'
      AvailabilityZone: !Select
        - 2
        - !GetAZs ''
      CidrBlock: !Select
        - 11
        - !Cidr
          - !GetAtt 'VPC.CidrBlock'
          - 16
          - 12
      Tags:
        - Key: Name
          Value: !Join
            - ':'
            - - !Ref 'Project'
              - subnet-alternate-C
        - Key: Environment
          Value: !Ref 'Environment'
        - Key: CreatedBy
          Value: CFN
Outputs:
  vpc:
    Value: !Ref 'VPC'
    Export:
      Name: vpc
  subnetpublica:
    Value: !Ref 'SubnetPublicA'
    Export:
      Name: subnet-public-A
  subnetpublicb:
    Condition: 2AZ
    Value: !Ref 'SubnetPublicB'
    Export: 
        Name: subnet-public-B
  subnetpublicc:
    Condition: 3AZ
    Value: !Ref 'SubnetPublicC'
    Export:
      Name: subnet-public-C
  subnetappa:
    Value: !Ref 'SubnetApplicationA'
    Export:
      Name: subnet-application-A
  subnetappb:
    Condition: 2AZ
    Value: !Ref 'SubnetApplicationB'
    Export:
      Name: subnet-application-B
  subnetappc:
    Condition: 3AZ
    Value: !Ref 'SubnetApplicationC'
    Export:
      Name: subnet-application-C
  subnetdba:
    Value: !Ref 'SubnetDatabaseA'
    Export:
      Name: subnet-database-A
  subnetdbb:
    Condition: 2AZ
    Value: !Ref 'SubnetDatabaseB'
    Export:
      Name: subnet-database-B
  subnetdbc:
    Condition: 3AZ
    Value: !Ref 'SubnetDatabaseC'
    Export:
      Name: subnet-database-C
  subnetreserveda:
    Value: !Ref 'SubnetAlternateA'
    Export:
      Name: subnet-alternate-A
  subnetreservedb:
    Condition: 2AZ
    Value: !Ref 'SubnetAlternateB'
    Export:
      Name: subnet-alternate-B
  subnetreservedc:
    Condition: 3AZ
    Value: !Ref 'SubnetAlternateC'
    Export:
      Name: subnet-alternate-C
